"""Gate 7 — signal monitoring dashboard. Renders PNG panels + an HTML report
summarizing every gate, with live-IC decay and retirement alerts.
"""
from __future__ import annotations
import os
from typing import Dict
import numpy as np
import pandas as pd

from config import CONFIG
from testing.decay import rolling_live_ic, ic_decay_curve
from testing.turnover import signal_to_weights, gross_net_sharpe


def _safe_mpl():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    return plt


def render_dashboard(signals: Dict[str, pd.DataFrame], composite: pd.DataFrame,
                     md, specs, tables: Dict[str, pd.DataFrame],
                     regimes: pd.Series, outdir: str = "outputs") -> str:
    os.makedirs(outdir, exist_ok=True)
    plt = _safe_mpl()

    # --- Panel 1: rolling live-IC for each signal (decay / crowding) ---
    fig, ax = plt.subplots(figsize=(11, 5))
    for name, sig in signals.items():
        rl = rolling_live_ic(sig, md, horizon=specs[name].horizon)
        ax.plot(rl.index, rl.values, label=name, alpha=0.8, lw=1.2)
    ax.axhline(0, color="k", lw=0.6)
    ax.set_title("Rolling 60d IC by signal (live-decay / crowding monitor)")
    ax.set_ylabel("rolling rank-IC")
    ax.legend(ncol=3, fontsize=7)
    fig.tight_layout(); p1 = os.path.join(outdir, "panel_live_ic.png")
    fig.savefig(p1, dpi=110); plt.close(fig)

    # --- Panel 2: composite cumulative net P&L + regime shading ---
    w = signal_to_weights(composite)
    fwd = md.returns.shift(-1)
    pnl = (w * fwd).sum(axis=1).fillna(0)
    cum = pnl.cumsum()
    fig, ax = plt.subplots(figsize=(11, 5))
    ax.plot(cum.index, cum.values, color="navy", lw=1.4, label="composite cum P&L")
    reg = regimes.reindex(cum.index).ffill()
    if reg.notna().any():
        crisis = reg == reg.max()
        ax.fill_between(cum.index, cum.min(), cum.max(), where=crisis.values,
                        color="red", alpha=0.08, label="crisis regime")
    ax.set_title("Composite alpha — cumulative gross P&L (regime-shaded)")
    ax.legend(fontsize=8)
    fig.tight_layout(); p2 = os.path.join(outdir, "panel_composite_pnl.png")
    fig.savefig(p2, dpi=110); plt.close(fig)

    # --- Panel 3: IC decay curves ---
    fig, ax = plt.subplots(figsize=(11, 5))
    for name, sig in signals.items():
        curve = ic_decay_curve(sig, md)
        ax.plot(curve.index, curve.values, marker="o", ms=3, label=name, alpha=0.8)
    ax.axhline(0, color="k", lw=0.6)
    ax.set_xlabel("forward horizon (days)"); ax.set_ylabel("mean rank-IC")
    ax.set_title("IC decay curves (holding-period selection)")
    ax.legend(ncol=3, fontsize=7)
    fig.tight_layout(); p3 = os.path.join(outdir, "panel_decay.png")
    fig.savefig(p3, dpi=110); plt.close(fig)

    # --- HTML report ---
    def to_html(df, title):
        return f"<h2>{title}</h2>" + df.round(4).to_html(index=False)

    html = ["<html><head><meta charset='utf-8'><title>Signal Research Report</title>",
            "<style>body{font-family:Arial;margin:30px;max-width:1100px}"
            "table{border-collapse:collapse;font-size:12px}td,th{border:1px solid #ccc;"
            "padding:3px 7px}h2{color:#16335c;margin-top:28px}img{max-width:100%}"
            ".pass{color:green;font-weight:bold}.fail{color:#b00}</style></head><body>",
            "<h1>Systematic Alpha Signal Discovery — Research Report</h1>",
            f"<p>Generated by quant_signals pipeline. Universe={md.prices.shape[1]} "
            f"names, {md.prices.shape[0]} days. Thresholds per house config.</p>"]
    titles = {"strength": "Gate 2 — Standalone strength (IC/IR/t/DSR/FDR)",
              "decay": "Gate 2b — Decay & holding period",
              "orthogonality": "Gate 3 — Orthogonality / incremental IC",
              "turnover": "Gate 4 — Turnover & cost-adjusted Sharpe",
              "regime": "Gate 5 — Regime conditional stability",
              "combination": "Gate 6 — Combiner benchmark (OOS, net of cost)"}
    for key, title in titles.items():
        if key in tables and tables[key] is not None and len(tables[key]):
            html.append(to_html(tables[key], title))
    html += [f"<h2>Monitoring panels</h2><img src='panel_live_ic.png'>",
             "<img src='panel_composite_pnl.png'>",
             "<img src='panel_decay.png'></body></html>"]
    path = os.path.join(outdir, "signal_research_report.html")
    with open(path, "w") as f:
        f.write("\n".join(html))
    return path
